[tool.poetry]
name = "soifunc"
version = "0.5.0"
description = "Soichiro's VapourSynth Functions Collection"
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
vapoursynth = ">=60"
vstools = ">=2.0.5"
vsscale = ">=1.7.2"
vsdenoise = ">=2.1.3"
vsrgtools = ">=1.4.2"
vsmasktools = ">=0.9.2"
vsdeband = ">=0.4.4"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
isort = "^5.11.4"
mypy = "^0.991"
pre-commit = "^2.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
